controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_api_weight:
    path: '/dashboard'
    controller: 'App\Controller\DashboardController::dashboardTrainer'
    methods: ['GET']